### ISSUE TITLE
[Slides] Refactoring Data Fetching - useEffect vs. Suspense for Data Fetching

### ISSUE THREAD

**Issue by meck93** [webplatformz/react-training-slides-v2#13]
We should consider refactoring the slides on data fetching due to the changes made by React 18.

**Comment by felixmokross** [comment]
In scope of this, a different exercise for the useEffect cleanup function is needed, ideally something that makes sense for the demo app. Idea: a timeout or interval is canceled when the component is unmounted.

**Comment by csalv22** [comment]
Idea for a useEffect sample:
`import { useState, useEffect, useCallback } from 'react';

function getWindowDimensions() {
  const { innerWidth: width, innerHeight: height } = window;
  return {
    width,
    height,
  };
}

export default function useWindowDimensions() {
  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());

  const handleResize = useCallback(() => {
    setWindowDimensions(getWindowDimensions());
  }, []);

  useEffect(() => {
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, [handleResize]);

  return windowDimensions;
}
`

**Comment by felixmokross** [comment]
@csalv22  looks good :-)
