### ISSUE TITLE
React Course: June 2022

### ISSUE THREAD

**Issue by meck93** [webplatformz/react-training-slides-v2#14]
- Intro: Felix
- App Setup: Moritz
- Demo App: Moritz
- First Components: Moritz
- Hooks: Felix
- Data Fetching: Felix
- Routing: Felix
- Form: Moritz
- State Management: Moritz
- Styling: Felix

**Comment by felixmokross** [comment]
Moved into https://github.com/webplatformz/react-training-slides-v2/issues/15

**Comment by meck93** [comment]
Cool 👍
