### ISSUE TITLE
[Slides]: Various Small Things

### ISSUE THREAD

**Issue by meck93** [webplatformz/react-training-slides-v2#18]
### General
- [x] fix chapter numbers -> there is no chapter 3
- [x] revert time schedule to Swiss time schedule
- [x] add Christoph as lecturer

#### Basic App Setup Chapter
- [x] Adjust ESLint Slides -> don’t show how to install it with CRA (it is implicitly installed)
- [x] Consider to provide better overview of rendering mechanisms in the beginning, e.g. client vs. server/pre-rendering. Introduce CRA as a simple way to build apps, but already hint at frameworks like Next.js.
   - See Various Chapter, where we already have some content for this. 
- [x] On JS Feature recap, add sample on array destructuring and spread syntax (destructuring is used with hooks)

#### Chapter 3: Demo App
- [x] Consider to remove Live Coding slides ("Let us help you") -- we don't really use this in the courses, screen sharing is simpler

#### Chapter 4: First Components
- [x] [Slide for first exercise](https://webplatformz.github.io/react-training-slides-v2/slides/05_First_Components.html#/1/3/0): is the command correct? The quotes should not be needed
- [x] ~~[List exercise](https://webplatformz.github.io/react-training-slides-v2/slides/05_First_Components.html#/4/1/2): the link to the full DTO from the API may confuse.~~
  - ~~A simpler list -- just an array of strings or very simple objects would be better. maybe just remove the link~~ <-- after reworking the whole chapter, it seems fine to me as-is.
- [x] add Recap slide at the end
- [x] add Questions slide at the end
- [x] check if all chapters have a recap and question slides!

#### Hooks Chapter
- [x] const [meal, setMeal] = useState<undefined | Meal>(); -> <undefined | Meal> is not necessary
  - const [meal, setMeal] = useState<Meal>(); is the same if we only want to say the initially meal can be undefined
  - const [meal, setMeal] = useState<undefined | Meal>(); allows to set the value to undefineds
- [x] ~~move useEffect to end and add useCallback~~ 
- [ ] Rules of Hooks: Don't return JSX from a hook (anti-pattern)?

#### Routing Chapter
- [x] Types don’t need to be installed anymore for router, remove the command
- [x] ~~useParams can be used without type parameter -- consider to do this to make things simpler. Maybe recommend using an a type parameter only as optionally and advanced usage (wouldn't do it in all cases and not needed for basic learning)~~

#### Forms Chapter
- [x] Fix links to controlled/uncontrolled form demo 

#### Pre Requisites überprüfen
- [x] Basic HTML & JS Kenntnisse

#### State Management Chapter
https://webplatformz.github.io/react-training-slides-v2/slides/10_State_Management.html#/4/3
- [x] ~~type useSWR<> -> also, in the solution~~ -> we are replacing useSWR with TanStack Query, so this task should be obsolete
- [x] Consider to use undefined for the initial context value instead of null? Because we also use it for the state -- course participant stumbled upon this inconsistency
- [x] Add description to this section: https://webplatformz.github.io/react-training-slides-v2/slides/10_State_Management.html#/2/1

**Comment by felixmokross** [comment]
> const [meal, setMeal] = useState(); is the same if we only want to say the initially meal can be undefined
> const [meal, setMeal] = useState<undefined | Meal>(); allows to set the value to undefineds

not sure if I understand this. In my opinion it should be just:

```
const [meal, setMeal] = useState<Meal>();
```

With this, setMeal also accepts undefined. But we don't need to specify undefined in the type argument, since the initial value is undefined.

**Comment by felixmokross** [comment]
>  Basic HTML & JS Kenntnisse

At least for JS we already have this stated in the course description. I think this should be sufficient.

**Comment by meck93** [comment]
I think it doesn't work. At least, VSCode & TypeScript complain about it. @felixmokross maybe you need to show me an example of it working? See my example below.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/22457755/188876367-d4a4258d-bf07-4292-a621-0eb054cb2afb.png">

> Error Message: "Argument of type 'undefined' is not assignable to parameter of type 'SetStateAction<Meal>'.ts(2345)"

Regarding your 2. question, no I have not created a hook that returns JSX so far.

**Comment by csalv22** [comment]
> Rules of Hooks: Don't return JSX from a hook (anti-pattern)?
is from my experience, but we can ignore it, just throwing every piece of experience into the course is not very helpfull.

If states are to be optional, I haven't managed to use those without the union undefined (| undefined). I suggest to amend that in the presentation.
