### ISSUE TITLE
Update Excercise Structure & Testing in Exercises

### ISSUE THREAD

**Issue by csalv22** [webplatformz/react-training-slides-v2#36]
### To Do
- [ ] Add to all Excercises a Stretch Goal
- [x] Check what Excercies should be combined (some relating to the first components) or potentially split up
- [ ] Add Presenter Notes with hints on what intermediate steps can be discussed or give more input to the implementation approach
- [x] Remove section on 'TDD' (only mention it as a side-note as it is not directly related to React)

### Additional 

- [x] ~~First Components: Add Testing Exercise/Solution to List Exercise: https://webplatformz.github.io/react-training-slides-v2/slides/05_First_Components.html#/7/4 -> Testing Solution is missing in the slides -> add solution with test that asserts the correct number of elements~~

**Comment by felixmokross** [comment]
I removed the following item as it is obsolete now (see #73)
> First Components: Add Testing Exercise/Solution to List Exercise: https://webplatformz.github.io/react-training-slides-v2/slides/05_First_Components.html#/7/4 -> Testing Solution is missing in the slides -> add solution with test that asserts the correct number of elements

**Comment by felixmokross** [comment]
As discussed, low priority
