### ISSUE TITLE
[Rendering/Architectures]: Add Slide to discuss 'CRA' alternatives 

### ISSUE THREAD

**Issue by meck93** [webplatformz/react-training-slides-v2#41]
- [ ] create a few slides on different React architectures
- [ ] give advice how a client's project (depending on its requirements) can benefit from a different rendering strategy than purely client-side rendering

**Comment by csalv22** [comment]
My impression from the last iteration was, that the way we handle it is atm quite allright. We currently mention next/remix as alternative & will switch to Vite in the next course iteration. And the other rendering strategies in the end chapter are fine imho
