### ISSUE TITLE
[Admin]: To do before next course

### ISSUE THREAD

**Issue by meck93** [webplatformz/react-training-slides-v2#5]
Things that need to be done before the next course: 

- [x] try out MS teams breakout rooms 
- [x] set up Miro board
- [x] set up Teams call with registered participants
- [x] send out email to registered participants with link to prerequisites slide
- [x] split up topics for presentation, esp. consider Simon's former topics "State Management" and "Styling"

**Comment by felixmokross** [comment]
We should set up a preparation session for these points
